import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Footer from './component/Footer'
import Navigate from "./component/navigate";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
        <Navigate/>
        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}
